---
name: User Story
description: Capture specific user needs with acceptance criteria
title: "[STORY]: "
labels: ["user-story"]
type: user-story
body:
  - type: markdown
    attributes:
      value: "# User Story"
  - type: textarea
    attributes:
      label: Story Statement
      description: Use standard user story format
      placeholder: "As a [role], I want [goal] so that [reason]"
  - type: textarea
    attributes:
      label: Acceptance Criteria
      description: "Mandatory completion checklist (Markdown supported)"
      placeholder: |
        - [ ] Criteria 1 (e.g., docs/AUDIT.md created)
        - [ ] Criteria 2
  - type: textarea
    attributes:
      label: Documentation Impact
      description: "Which docs need updating? (e.g., docs/INFRA.md)"
      placeholder: "- docs/FILE.md"